apiVersion: aristi.cloudstation/v1alpha1
kind: Aristi
metadata:
  labels:
    app.kubernetes.io/name: aristi
    app.kubernetes.io/managed-by: kustomize
  name: aristi-sample
  namespace: default
spec:
  gateway:
    name: argo-gateway
    spec:
      selector:
        istio: ingressgateway # use the default IngressGateway
      servers:
        - port:
            number: 80
            name: http
            protocol: HTTP
          hosts:
            - "*"
  istio:
    hosts:
      - "*"
    gateways:
      - argo-gateway
    virtualService:
      name: rollout-vsvc
      routes:
        - destination:
            host: weather-test-app-hyd
          weight: 10
        - destination:
            host: weather-test-app-ny
          weight: 90
  rollout:
    services:
      stable:
        name: weather-test-app-hyd
        ports:
          - protocol: "TCP"
            port: 80
            targetPort: 5000
        type: ClusterIP
      canary:
        name:  weather-test-app-ny
        ports:
          - protocol: "TCP"
            port: 80
            targetPort: 5000
        type: ClusterIP
    selector:
      matchLabels:
        app: rollout-istio
    replicas: 2
    template:
      metadata:
        labels:
          app: rollout-istio
      spec:
        containers:
          - name: weather-app-falcon
            image: docker.io/atulinfracloud/weathersample:v1
    strategy:
      canary:
        canaryService: weather-test-app-ny
        stableService: weather-test-app-hyd
        steps:
          - setWeight: 50
          - pause:
              duration: "10m"